### ISSUE TITLE
Error : 

### ISSUE THREAD

**Issue by geeksinsights** [oravirt/vagrant-vbox-si-fs#1]
Hi

I am new to ansible. I followed all steps mentioned in the read me. however I am getting this errors

I provisioned with the steps setup=True and vagrant up, however it has not provisioned the database nor installed, just simply provisioned the box.

So I have ssh into the box and trying to run the playbook, and this is the error.

**I am using windows 10 and I checked the ansible version in the box is 2.5.5**

[vagrant@db-fs-1 ansible-oracle]$ ansible-playbook vbox-si-fs-install.yml -e vbox-si-fs -i inventory/db-fs-1
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/vagrant/extra-provision/ansible-oracle/roles/oradb-manage-pdb/tasks/main.yml': line 23, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Manage pdb(s)
  ^ here

**Comment by oravirt** [comment]
Hi,

Unfortunately, I can't re-produce your error, but the error typically means that the playbook cant find the module, in this case `oracle_pdb`. It should be located in the `library` folder along with all the other modules.

However, I found an error in the documentation (`set setup=True`, should be `set setup=true`) which is fixed now. SO, that should fix the problem with the initial provisioning (I just tested it on a win 10 system)

So please try again and let me know how it goes.
Thanks!
/M

**Comment by geeksinsights** [comment]
Hi

Thanks for the reply

I fixed the initial error, as you said its modules not copied to ansible_oracle.

Due to setup=True , provisioning is not happening, only boxes are provisioned. 

Marking as closed.

-Thanks
Suresh
